version: "3"
services:                         
  node:            
    image: "node:14"   
    working_dir: /home/node/app
    environment:                              
      - NODE_ENV=production       
    volumes:          
      - ./:/home/node/app             
    command: "node index.js"
