version: '3'
services:
  mqtt:
    # not using 2.x yet as it has some breaking change es such as the required
    # listener to bind 0.0.0.0
    image: eclipse-mosquitto:1.6.12
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
